### PR TITLE
[WIP] add ui for login/logout

### PR DESCRIPTION
**Pull request by andrico1234**
Todo: 

[ ] test on different devices and browsers

### CODE REVIEW

**Comment by suhaga15** [comment]
CHROME ON DESKTOP:

- https://calisthenics-skills-prod.eu.auth0.com/user/ssodata returned a 404 code when I hit 
   calisthenicsskills.com/login

- The following error showed up in the console post logging in:
```
err FirebaseError: Messaging: The required permissions were not granted and blocked instead. (messaging/permission-blocked).
    at e.<anonymous> (https://calisthenicsskills.com/app-76d3d98eb3e05152986a.js:1:317075)
    at https://calisthenicsskills.com/app-76d3d98eb3e05152986a.js:1:3513
    at Object.next (https://calisthenicsskills.com/app-76d3d98eb3e05152986a.js:1:3618)
    at s (https://calisthenicsskills.com/app-76d3d98eb3e05152986a.js:1:2389)
```
The above console log is happening at line 83 in src/components/FirebaseNotifications.tsx

No issues with the functionality

**Comment by andrico1234** [comment]
Thanks! That's an issue with enabling notifications, which is unrelated to authentication/authorization! This error may be a result of a user declining to receive notifications when the prompt appears on first visit to the site

**Comment by suhaga15** [comment]
Ah yes that makes sense. I didn't hit allow notifications when the prompt showed up

**Comment by suhaga15** [comment]
FIREFOX ON DESKTOP:

Absolutely no issues with logging in or signing up. No errors shown on the console either.

However, that old bug where videos don't work unless firefox is in full screen mode is still present

**Comment by suhaga15** [comment]
SAFARI ON DESKTOP:

- When I tried logging in to the accounts that I created on Chrome/Firefox, I was successfully logged in and redirected to calisthenicsskills.com/callback/ but it didn't load any content at all. Not even the topbar or the sidebar. Refreshing the page didn't load the content either. 

- I explicitly had to type calisthenicsskills.com/login/ in the address bar after signing in for the content to be loaded. I've taken screenshots. Full screen mode made no difference. Console error showed invalid callback

- Website stopped loading after I spent a long time on the calisthenicsskills.com/callback/ page. Even when I hit logout, the page becomes unresponsive and doesn't log me out or load anything. Nothing shown on the console.

- Had to clear my cache to load the site again. I was logged in even though I cleared my cache. I need to clear cache after every subsequent login/logout. I'm able to successfully login and use the website using the account I created on Safari on other browsers however.

**Pull request merged**
